# Generated by Django 2.2.5 on 2019-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostLike',
        ),
    ]
