# Generated by Django 2.2.5 on 2019-10-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191019_1425'),
        ('polls', '0002_choice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.AppUser'),
            preserve_default=False,
        ),
    ]
